pipeline {
    agent {
        node {
            label SLAVE
        }
    }
    stages {
        stage('Set build description') {
            steps {
                script {
                    currentBuild.description = "<b>Parameter File = ${parameters_file}<br>Pipeline Template = ${pipeline_template}</b>"
                }
            }
        }

        stage('Rollout or Update spinnaker pipelines') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'spinnaker_cli_creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                  echo 'Set up spin cli config file'
                  sh 'sh ${WORKSPACE}/configure_spin_cli_config.sh \"${USER}\" \"${PASS}\"'
                  echo 'Rolling out spinnaker pipeline changes...'
                  sh 'docker run -v ${WORKSPACE}/.spin/config:/root/.spin/config:ro --rm armdocker.rnd.ericsson.se/proj_openstack_tooling/common_cicd_automation_pipeline:latest python3 -m spinnaker_pipeline_creation create-or-update-pipeline -ar \"${area}\" -fl \"${flows}\" -pf \"${parameters_file}\" -ptf \"${pipeline_template}\"'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}